# Makefile fragment to set the version number and release date
# (needed for building a distribution, documentation, etc.)

# $Id: Makefile.version,v 1.6 1999/11/29 03:00:48 greg Rel $

VERSION = 0.32
VERSION_SYM = 0_32
RELEASE_DATE = 28 November, 1999
