# Makefile fragment to set the version number and release date
# (needed for building a distribution, documentation, etc.)

# $Id: Makefile.version,v 1.4 1999/03/12 00:57:58 greg Rel $

VERSION = 0.30
VERSION_SYM = 0_30
RELEASE_DATE = 12 March, 1999
